name: CI Pipeline

on:
    push:
        branches: ["main"]

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: python,install
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: make install
          

      - name: init
        run: make init